cinema/cinema.loc/src/Entity/Seanse.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeanseRepository")
 */
class Seanse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $movie_id;

    /**
     * @ORM\Column(type="time")
     */
    private $time;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMovieId(): ?int
    {
        return $this->movie_id;
    }

    public function setMovieId(int $movie_id): self
    {
        $this->movie_id = $movie_id;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(\DateTimeInterface $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }
}

cinema/cinema.loc/src/Form/SeanseType.php
<?php

namespace App\Form;

use App\Entity\Seanse;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeanseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('movie_id')
            ->add('time')
            ->add('date')
            ->add('price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Seanse::class,
        ]);
    }
}

cinema/cinema.loc/src/Controller/Admin/SeanseController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class SeanseController extends AbstractController
{
    /**
     * @Route("/admin/seanse", name="admin_seanse")
     */
    public function index()
    {
        return $this->render('admin/seanse/index.html.twig', [
            'controller_name' => 'SeanseController',
        ]);
    }
}

cinema/cinema.loc/src/Controller/SeanseController.php
<?php

namespace App\Controller;

use App\Entity\Seanse;
use App\Form\SeanseType;
use App\Repository\SeanseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/seanse")
 */
class SeanseController extends AbstractController
{
    /**
     * @Route("/", name="seanse_index", methods={"GET"})
     */
    public function index(SeanseRepository $seanseRepository): Response
    {
        return $this->render('seanse/index.html.twig', [
            'seanses' => $seanseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="seanse_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $seanse = new Seanse();
        $form = $this->createForm(SeanseType::class, $seanse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($seanse);
            $entityManager->flush();

            return $this->redirectToRoute('seanse_index');
        }

        return $this->render('seanse/new.html.twig', [
            'seanse' => $seanse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="seanse_show", methods={"GET"})
     */
    public function show(Seanse $seanse): Response
    {
        return $this->render('seanse/show.html.twig', [
            'seanse' => $seanse,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="seanse_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Seanse $seanse): Response
    {
        $form = $this->createForm(SeanseType::class, $seanse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('seanse_index');
        }

        return $this->render('seanse/edit.html.twig', [
            'seanse' => $seanse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="seanse_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Seanse $seanse): Response
    {
        if ($this->isCsrfTokenValid('delete'.$seanse->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($seanse);
            $entityManager->flush();
        }

        return $this->redirectToRoute('seanse_index');
    }
}

cinema/cinema.loc/templates/seanse/_delete_form.html.twig
<form method="post" action="{{ path('seanse_delete', {'id': seanse.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ seanse.id) }}">
    <button class="btn">Delete</button>
</form>

cinema/cinema.loc/templates/seanse/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

cinema/cinema.loc/templates/seanse/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Seanse{% endblock %}

{% block body %}
    <h1>Edit Seanse</h1>

    {{ include('seanse/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('seanse_index') }}">back to list</a>

    {{ include('seanse/_delete_form.html.twig') }}
{% endblock %}

cinema/cinema.loc/templates/seanse/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seanse index{% endblock %}

{% block body %}
    <h1>Seanse index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Movie_id</th>
                <th>Time</th>
                <th>Date</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for seanse in seanses %}
            <tr>
                <td>{{ seanse.id }}</td>
                <td>{{ seanse.movieId }}</td>
                <td>{{ seanse.time ? seanse.time|date('H:i:s') : '' }}</td>
                <td>{{ seanse.date ? seanse.date|date('Y-m-d') : '' }}</td>
                <td>{{ seanse.price }}</td>
                <td>
                    <a href="{{ path('seanse_show', {'id': seanse.id}) }}">show</a>
                    <a href="{{ path('seanse_edit', {'id': seanse.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('seanse_new') }}">Create new</a>
{% endblock %}

cinema/cinema.loc/templates/seanse/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Seanse{% endblock %}

{% block body %}
    <h1>Create new Seanse</h1>

    {{ include('seanse/_form.html.twig') }}

    <a href="{{ path('seanse_index') }}">back to list</a>
{% endblock %}

cinema/cinema.loc/templates/seanse/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seanse{% endblock %}

{% block body %}
    <h1>Seanse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ seanse.id }}</td>
            </tr>
            <tr>
                <th>Movie_id</th>
                <td>{{ seanse.movieId }}</td>
            </tr>
            <tr>
                <th>Time</th>
                <td>{{ seanse.time ? seanse.time|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ seanse.date ? seanse.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ seanse.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('seanse_index') }}">back to list</a>

    <a href="{{ path('seanse_edit', {'id': seanse.id}) }}">edit</a>

    {{ include('seanse/_delete_form.html.twig') }}
{% endblock %}