cinema/cinema.loc/src/Entity/Orders.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrdersRepository")
 */
class Orders
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $hall_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $seanse_id;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $total_price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getHallId(): ?int
    {
        return $this->hall_id;
    }

    public function setHallId(int $hall_id): self
    {
        $this->hall_id = $hall_id;

        return $this;
    }

    public function getSeanseId(): ?int
    {
        return $this->seanse_id;
    }

    public function setSeanseId(int $seanse_id): self
    {
        $this->seanse_id = $seanse_id;

        return $this;
    }

    public function getTotalPrice(): ?string
    {
        return $this->total_price;
    }

    public function setTotalPrice(string $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }
}

cinema/cinema.loc/src/Form/OrdersType.php
<?php

namespace App\Form;

use App\Entity\Orders;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrdersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('customer_id')
            ->add('hall_id')
            ->add('seanse_id')
            ->add('total_price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Orders::class,
        ]);
    }
}

cinema/cinema.loc/src/Controller/Admin/OrdersController.php
<?php

namespace App\Controller\Admin;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class OrdersController extends AbstractController
{
    /**
     * @Route("/admin/orders", name="admin_orders")
     */
    public function index()
    {
        return $this->render('admin/orders/index.html.twig', [
            'controller_name' => 'OrdersController',
        ]);
    }
}

cinema/cinema.loc/src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\Orders;
use App\Form\OrdersType;
use App\Repository\OrdersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/orders")
 */
class OrdersController extends AbstractController
{
    /**
     * @Route("/", name="orders_index", methods={"GET"})
     */
    public function index(OrdersRepository $ordersRepository): Response
    {
        return $this->render('orders/index.html.twig', [
            'orders' => $ordersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="orders_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $order = new Orders();
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('orders_index');
        }

        return $this->render('orders/new.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="orders_show", methods={"GET"})
     */
    public function show(Orders $order): Response
    {
        return $this->render('orders/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="orders_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Orders $order): Response
    {
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('orders_index');
        }

        return $this->render('orders/edit.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="orders_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Orders $order): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('orders_index');
    }
}

cinema/cinema.loc/templates/orders/_delete_form.html.twig
<form method="post" action="{{ path('orders_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

cinema/cinema.loc/templates/orders/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

cinema/cinema.loc/templates/orders/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Orders{% endblock %}

{% block body %}
    <h1>Edit Orders</h1>

    {{ include('orders/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('orders_index') }}">back to list</a>

    {{ include('orders/_delete_form.html.twig') }}
{% endblock %}

cinema/cinema.loc/templates/orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders index{% endblock %}

{% block body %}
    <h1>Orders index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Customer_id</th>
                <th>Hall_id</th>
                <th>Seanse_id</th>
                <th>Total_price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.customerId }}</td>
                <td>{{ order.hallId }}</td>
                <td>{{ order.seanseId }}</td>
                <td>{{ order.totalPrice }}</td>
                <td>
                    <a href="{{ path('orders_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('orders_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('orders_new') }}">Create new</a>
{% endblock %}

cinema/cinema.loc/templates/orders/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Orders{% endblock %}

{% block body %}
    <h1>Create new Orders</h1>

    {{ include('orders/_form.html.twig') }}

    <a href="{{ path('orders_index') }}">back to list</a>
{% endblock %}

cinema/cinema.loc/templates/orders/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    <h1>Orders</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Customer_id</th>
                <td>{{ order.customerId }}</td>
            </tr>
            <tr>
                <th>Hall_id</th>
                <td>{{ order.hallId }}</td>
            </tr>
            <tr>
                <th>Seanse_id</th>
                <td>{{ order.seanseId }}</td>
            </tr>
            <tr>
                <th>Total_price</th>
                <td>{{ order.totalPrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('orders_index') }}">back to list</a>

    <a href="{{ path('orders_edit', {'id': order.id}) }}">edit</a>

    {{ include('orders/_delete_form.html.twig') }}
{% endblock %}